### ISSUE TITLE
hostname in kubernetes

### ISSUE THREAD

**Issue by lazedo** [kamailio/kamailio#2119]
### Description

gethostname not accurate in kubernetes

#### Reproduction

on a recent test with kamailio in kubernetes, found that gethostname can return only the hostname and not the fqdn. this depends on the kind of object is used (deployment/statefulset)

### Possible Solutions

the below patch fixed the issues i was having

```
diff --git a/src/modules/ipops/ipops_pv.c b/src/modules/ipops/ipops_pv.c
index 5f77aa9..f65b4dd 100644
--- a/src/modules/ipops/ipops_pv.c
+++ b/src/modules/ipops/ipops_pv.c
@@ -455,6 +455,11 @@
 	if (gethostname(hbuf, 512)<0) {
 		LM_WARN("gethostname failed - host pvs will be null\n");
 		return -1;
+	} else {
+		struct hostent* h;
+		if((h = gethostbyname(hbuf)) != NULL) {
+			memcpy(hbuf, h->h_name, 512);
+		}
 	}
 
 	hlen = strlen(hbuf);

```

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```
latest master
```

* **Operating System**:

```
buster & centos7
```

**Comment by miconda** [comment]
I haven't investigated the issue, nor the fix, but I know that use if gethostbyname() is no longer recommended, being marked as obsolete:

  * http://man7.org/linux/man-pages/man3/gethostbyname.3.html

```
       The gethostbyname*(), gethostbyaddr*(), herror(), and hstrerror()
       functions are obsolete.  Applications should use getaddrinfo(3),
       getnameinfo(3), and gai_strerror(3) instead.
```

At some point we should consider replacing these obsolete functions where they are already used in the code, but for now we should try not to add more use of them...

**Comment by sergey-safarov** [comment]
Could you try look this output.
```sh
[safarov@safarov-dell ~]$ kubectl exec -it proxy-dc0-0 -- sh
Defaulting container name to proxy.
Use 'kubectl describe pod/proxy-dc0-0 -n ippbx' to see all of the containers in this pod.
/ # hostname -f
proxy-dc0-0.proxy-dc0.ippbx.svc.cluster.local
/ # hostname
proxy-dc0-0
```
Here pod `proxy-dc0-0` member of `proxy-dc0` statefulset in `ippbx` namespace.
Think `kamailio` may use similar API calls.

**Comment by sergey-safarov** [comment]
Here output of strace command
```
/ # strace hostname -f
execve("/bin/hostname", ["hostname", "-f"], 0x7ffd0fb7df78 /* 84 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x7f36d29e7d48) = 0
set_tid_address(0x7f36d29e831c)         = 34
mprotect(0x7f36d29e4000, 4096, PROT_READ) = 0
mprotect(0x564ae99b0000, 16384, PROT_READ) = 0
getuid()                                = 0
uname({sysname="Linux", nodename="test-st-0", ...}) = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "# Kubernetes-managed hosts file."..., 1024) = 248
read(3, "", 1024)                       = 0
close(3)                                = 0
open("/etc/hosts", O_RDONLY|O_CLOEXEC)  = 3
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
read(3, "# Kubernetes-managed hosts file."..., 1024) = 248
read(3, "", 1024)                       = 0
close(3)                                = 0
ioctl(1, TIOCGWINSZ, {ws_row=41, ws_col=173, ws_xpixel=0, ws_ypixel=0}) = 0
writev(1, [{iov_base="test-st-0.test-st.ippbx.svc.clus"..., iov_len=41}, {iov_base="\n", iov_len=1}], 2test-st-0.test-st.ippbx.svc.cluster.local
) = 42
exit_group(0)                           = ?
+++ exited with 0 +++
```
Looks as `hostname -f` take value from `/etc/hosts` file
```
/ # cat /etc/hosts
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.21.0.141	test-st-0.test-st.ippbx.svc.cluster.local	test-st-0
```
Test made using this statefulset.
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-st
spec:
  podManagementPolicy: Parallel
  serviceName: test-st
  replicas: 1
  selector:
    matchLabels:
      app: test-st
  template:
    metadata:
      labels:
        app: test-st
    spec:
      containers:
      - name: proxy
        securityContext:
          privileged: true
        image: kamailio/kamailio-ci:master-alpine.debug
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
        args:
          - "-c"
          - "sleep 360000000000"
```
