### ISSUE TITLE
Segmentation fault while writing accounting data to syslog using acc_json module

### ISSUE THREAD

**Issue by mshary** [kamailio/kamailio#3292]
### Description

We have a rare crash in kamailio v5.3 running on Debian Buster in production environment. The crash (segmentation fault) happens while app_json module is writing accounting data to syslog upon receiving ACK for successful INVITE transaction over IPv6 UDP socket.

### Troubleshooting
We checked the server health and service load at the time of crash, everything looks normal. We inspected the core dump generated by kamailio, and it seems that there is some sort of race condition causing the crash, the ACK completes the INVITE transaction, so kamailio was fetching the transaction data from memory to write accounting record to syslog, however, that data is corrupted or deleted by some other kamailio process. We do not see anything unusual in kamailio log related to crash. Perhaps it is related to this older but [unresolved crash report](https://github.com/kamailio/kamailio/issues/2998). 

#### Reproduction
No, we are unable to reproduce it in our lab.

#### Debugging Data

Output of `bt full` (first 16 function traces),

```gdb
#0  0x0000561a11a47ec7 in match_by_name (avp=0xd, id=52, name=0x7ffccc7967f8) at core/usr_avp.c:379
        avp_name = 0x7f10ead4f190
#1  0x0000561a11a48d15 in search_next_avp (s=0x7ffccc7967f0, val=0x7ffccc7967d0) at core/usr_avp.c:500
        matched = 0
        avp = 0x7f10ead4f180
        list = 0x7f10dc3196a8
        __func__ = "search_next_avp"
#2  0x0000561a11a486d1 in search_avp (ident=..., val=0x7ffccc7967d0, state=0x7ffccc7967f0) at core/usr_avp.c:466
        ret = 0x7f10ead4f180
        st = {flags = 273, id = 10, name = {n = -567873331, s = {s = 0x7f11de26f0cd "mapped_identity_user)", len = 20}, re = 0x7f11de26f0cd}, avp = 0x7f10f0114820}
        list = 0x7f10f4d2b208
        __func__ = "search_avp"
#3  0x0000561a11a4804b in search_first_avp (flags=1, name=..., val=0x7ffccc7967d0, s=0x7ffccc7967f0) at core/usr_avp.c:415
        id = {flags = 1, name = {n = -573917191, s = {s = 0x7f11ddcab7f9 "from_mandant);tm", len = 12}, re = 0x7f11ddcab7f9}, index = 0}
#4  0x00007f11dcfb0392 in pv_get_avp (msg=0x7f11de70c4b0, param=0x7f11de6cf7b0, res=0x7ffccc796930) at pv_core.c:1793
        name_type = 1
        avp_name = {n = -573917191, s = {s = 0x7f11ddcab7f9 "from_mandant);tm", len = 12}, re = 0x7f11ddcab7f9}
        avp_value = {n = -563284264, s = {s = 0x7f11de6cf6d8 "", len = -563034960}, re = 0x7f11de6cf6d8}
        avp = 0x2000000
        avp_value0 = {n = -864458672, s = {s = 0x7ffccc796850 "\300hy\314\374\177", len = -587590620}, re = 0x7ffccc796850}
        avp0 = 0x7f11dcd1bc90 <val_arr+336>
        idx = 0
        idxf = 0
        p = 0x14d0960 <error: Cannot access memory at address 0x14d0960>
        p_ini = 0x8f6c38 <error: Cannot access memory at address 0x8f6c38>
        p_size = 22042
        n = 0
        state = {flags = 497, id = 52, name = {n = -573917191, s = {s = 0x7f11ddcab7f9 "from_mandant);tm", len = 12}, re = 0x7f11ddcab7f9}, avp = 0xd}
        __func__ = "pv_get_avp"
#5  0x0000561a11a77f17 in pv_get_spec_value (msg=0x7f11de70c4b0, sp=0x7f11de6cf798, value=0x7ffccc796930) at core/pvapi.c:1404
        ret = 0
        __func__ = "pv_get_spec_value"
#6  0x00007f11dcd0c43a in extra2strar (extra=0x7f11de6cf788, rq=0x7f11de70c4b0, val_arr=0x7f11dcd1bb90 <val_arr+80>, int_arr=0x7f11dcd1c4d4 <int_arr+20>, 
    type_arr=0x7f11dcd1c725 <type_arr+5> "\002\002\002\002\002\002\002\002\001") at acc_extra.c:222
        value = {rs = {s = 0x0, len = 0}, ri = 0, flags = 0}
        n = 18
        i = 0
        __func__ = "extra2strar"
#7  0x00007f11dc2afc85 in acc_json_send_request (req=0x7f11de70c4b0, inf=0x7ffccc796af0) at acc_json_mod.c:308
        attr_cnt = 5
        i = 5
        m = 0
        o = 0
        object = 0x561a13e7b7f0
        __func__ = "acc_json_send_request"
        extra = 0x561a11c6f34a
#8  0x00007f11dcce5a84 in acc_run_engines (msg=0x7f11de70c4b0, type=0, reset=0x0) at acc.c:581
        inf = {env = 0x7f11dcd423a0 <acc_env>, varr = 0x7f11dcd1bb40 <val_arr>, iarr = 0x7f11dcd1c4c0 <int_arr>, tarr = 0x7f11dcd1c720 <type_arr> "\002\002\002\002\001\002\002\002\002\002\002\002\002\001", 
          leg_info = 0x0}
        e = 0x7f11de6cfa10
        __func__ = "acc_run_engines"
#9  0x00007f11dccf90a4 in acc_onack (t=0x7f10f4d2b008, req=0x7f10f52e2620, ack=0x7f11de70c4b0, code=-4) at acc_logic.c:657
        __func__ = "acc_onack"
#10 0x00007f11dccf959c in tmcb_func (t=0x7f10f4d2b008, type=4, ps=0x7ffccc796d10) at acc_logic.c:696
        __func__ = "tmcb_func"
#11 0x00007f11dd158e87 in run_trans_callbacks_internal (cb_lst=0x7f10f4d2b080, type=4, trans=0x7f10f4d2b008, params=0x7ffccc796d10) at t_hooks.c:254
        cbp = 0x7f10f70688d8
        backup_from = 0x561a11d83f30 <def_list+16>
        backup_to = 0x561a11d83f38 <def_list+24>
        backup_dom_from = 0x561a11d83f40 <def_list+32>
        backup_dom_to = 0x561a11d83f48 <def_list+40>
        backup_uri_from = 0x561a11d83f20 <def_list>
        backup_uri_to = 0x561a11d83f28 <def_list+8>
        backup_xavps = 0x561a11d16180 <_xavp_list_head>
        __func__ = "run_trans_callbacks_internal"
#12 0x00007f11dd158fae in run_trans_callbacks (type=4, trans=0x7f10f4d2b008, req=0x7f11de70c4b0, rpl=0x0, code=-4) at t_hooks.c:279
        params = {req = 0x7f11de70c4b0, rpl = 0x0, param = 0x7f10f70688e8, code = -4, flags = 0, branch = 0, t_rbuf = 0x0, dst = 0x0, send_buf = {s = 0x0, len = 0}}
#13 0x00007f11dd0bd4b4 in t_newtran (p_msg=0x7f11de70c4b0) at t_lookup.c:1437
        lret = -2
        my_err = -562995536
        canceled = 0
        __func__ = "t_newtran"
#14 0x00007f11dd14fb4b in t_relay_to (p_msg=0x7f11de70c4b0, proxy=0x0, proto=0, replicate=0) at t_funcs.c:243
        ret = 0
        new_tran = 32764
        t = 0x7f11de70c4b0
        dst = {send_sock = 0x561a11867b90 <_start>, to = {s = {sa_family = 43008, sa_data = "_V\004\271f\377\000\000\000\000\000\000\000"}, sin = {sin_family = 43008, sin_port = 22111, sin_addr = {
                s_addr = 4284922116}, sin_zero = "\000\000\000\000\000\000\000"}, sin6 = {sin6_family = 43008, sin6_port = 22111, sin6_flowinfo = 4284922116, sin6_addr = {__in6_u = {
                  __u6_addr8 = '\000' <repeats 15 times>, __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 294026128}, sas = {ss_family = 43008, 
              __ss_padding = "_V\004\271f\377", '\000' <repeats 16 times>, "\220{\206\021\032V\000\000\260^q\336\021\177\000\000H\221?\336\021\177\000\000\030\203\017\336\021\177", '\000' <repeats 14 times>, "\032V\000\000\000\000\000\002\000\000\000\000\000\250_V\004\271f\377\030e\217", '\000' <repeats 13 times>, "\220{\206\021\032V\000\000p\223y\314\374\177\000", __ss_align = 0}}, id = 0, send_flags = {f = 0, 
            blst_imask = 0}, proto = -128 '\200', proto_pad0 = 111 'o', proto_pad1 = -13191}
        port = 0
        host = {s = 0x2 <error: Cannot access memory at address 0x2>, len = 0}
        comp = 0
        __func__ = "t_relay_to"
#15 0x00007f11dd1737b4 in _w_t_relay_to (p_msg=0x7f11de70c4b0, proxy=0x0, force_proto=0) at tm.c:1691
        t = 0x7f11de70c4b0
        res = 0
        __func__ = "_w_t_relay_to"
#16 0x00007f11dd174aab in w_t_relay (p_msg=0x7f11de70c4b0, _foo=0x0, _bar=0x0) at tm.c:1891
No locals.

```
Module parameters for `acc_json`,

```python
# -- acc_json CDR parameters --
modparam("acc_json", "acc_output_syslog", 1)
modparam("acc_json", "acc_flag", 1)
modparam("acc_json", "acc_log_facility", ACC_JSON_FACILITY)
modparam("acc_json", "acc_extra", "iu=$ou;ou=$ru;f=$fu;t=$tu;cq=$cs;id=$avp(identity_user);mi=$avp(mapped_identity_user);fp=$avp(from_provider);fs=$mf;ld=$avp(lastdst);u1=$ua;u2=$avp(ua_rsp);x1=$hdr(X-RTP-Stat);x2=$avp(xrtp_rsp);xt1=$hdr(X-RTP-Stat-Add);xt2=$avp(xrtp_add_rsp);tt=$avp(target);ct=$ct;fm=$avp(from_mandant);tm=$avp(to_mandant);mc=$avp(m_target)")

``` 

#### Log Messages

```RUST
Nov 28 16:11:59 sip-proxy2 kamailio[1370]: ALERT: <core> [main.c:766]: handle_sigs(): child process 1596 exited by a signal 11
Nov 28 16:11:59 sip-proxy2 kamailio[1370]: ALERT: <core> [main.c:769]: handle_sigs(): core was generated
```

#### SIP Traffic

```YAML
INVITE sip:4900000000@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx];uniq=8ED0C01913346AA654117F901E24D SIP/2.0
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
History-Info: <sip:+4900000000@sip-proxy.de>;index=1
History-Info: <sip:+4900000000@sip-proxy.de;user=phone>;index=1.1;np=1
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.46e0b6bab175e9465a766f3602eb1723.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.fbdcb55027bdeb56205b8bd53e09641b.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.c1356dc9c4dd64165b1d2a7b6dcc8061.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bKud6dm320bogcnc1dqvu0.1
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
From: "+491111111111"<sip:+491111111111@sip-server.de;transport=udp;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000"<sip:+4900000000@sip-proxy.de;user=phone>
CSeq: 1 INVITE
Max-Forwards: 61
P-Early-Media: supported
Contact: <sip:+491111111111@ee.eee.eee.ee:5060;user=phone;transport=udp>
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,INFO,PRACK,NOTIFY,MESSAGE,REFER,UPDATE
Supported: timer
Min-SE: 90
Session-Expires: 1800;refresher=uac
Content-Length: 550
Content-Type: application/sdp

v=0
o=- 1159782858 1 IN IP6 aaaa:aaa:aaa:a:aaa:aaa:aaa:aa
s=-
c=IN IP6 aaaa:aaa:aaa:a:aaa:aaa:aaa:aa
b=RR:3000
b=RS:1000
b=AS:80
t=0 0
a=rtpengine:dda0c1ad4f21
m=audio 20798 RTP/AVP 9 8 96 0 110
b=RR:1837
b=RS:612
b=AS:80
a=maxptime:240
a=msi:mavodi-0-15b-89-6-ffffffff-b5930000-5e88bfbb24c0a-948-ffffffffffffffff-@ff.fff.fff.f-gg.ggg.ggg.g;UAGLEJ04-24
a=rtpmap:9 G722/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 G726-32/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:110 telephone-event/8000
a=fmtp:110 0-15
a=sendrecv
a=rtcp:20799
a=ptime:20


SIP/2.0 100 Trying
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.46e0b6bab175e9465a766f3602eb1723.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.fbdcb55027bdeb56205b8bd53e09641b.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.c1356dc9c4dd64165b1d2a7b6dcc8061.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bKud6dm320bogcnc1dqvu0.1
From: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 1 INVITE
User-Agent: AVM FRITZ!Box 7490 (UI) 113.07.29 (Oct 26 2021)
Content-Length: 0


SIP/2.0 180 Ringing
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.46e0b6bab175e9465a766f3602eb1723.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.fbdcb55027bdeb56205b8bd53e09641b.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.c1356dc9c4dd64165b1d2a7b6dcc8061.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bKud6dm320bogcnc1dqvu0.1
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
From: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 1 INVITE
Contact: <sip:4900000000@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx];uniq=8ED0C01913346AA654117F901E24D>
User-Agent: AVM FRITZ!Box 7490 (UI) 113.07.29 (Oct 26 2021)
Content-Length: 0


SIP/2.0 200 OK
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.46e0b6bab175e9465a766f3602eb1723.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.fbdcb55027bdeb56205b8bd53e09641b.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.c1356dc9c4dd64165b1d2a7b6dcc8061.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bKud6dm320bogcnc1dqvu0.1
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
From: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 1 INVITE
Contact: <sip:4900000000@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx];uniq=8ED0C01913346AA654117F901E24D>
User-Agent: AVM FRITZ!Box 7490 (UI) 113.07.29 (Oct 26 2021)
Supported: 100rel,replaces
Allow-Events: telephone-event,refer
Allow: INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
Content-Type: application/sdp
Accept: application/sdp, multipart/mixed
Accept-Encoding: identity
Content-Length:   277

v=0
o=user 12824182 12824182 IN IP6 xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
s=-
c=IN IP6 xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
t=0 0
m=audio 7078 RTP/AVP 8 110
a=rtpmap:8 PCMA/8000
a=rtpmap:110 telephone-event/8000
a=fmtp:110 0-15
a=sendrecv
a=rtcp:7079
a=ptime:20


SIP/2.0 200 OK
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.46e0b6bab175e9465a766f3602eb1723.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.fbdcb55027bdeb56205b8bd53e09641b.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.c1356dc9c4dd64165b1d2a7b6dcc8061.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bKud6dm320bogcnc1dqvu0.1
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
From: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 1 INVITE
Contact: <sip:4900000000@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx];uniq=8ED0C01913346AA654117F901E24D>
User-Agent: AVM FRITZ!Box 7490 (UI) 113.07.29 (Oct 26 2021)
Supported: 100rel,replaces
Allow-Events: telephone-event,refer
Allow: INVITE,ACK,OPTIONS,CANCEL,BYE,UPDATE,PRACK,INFO,SUBSCRIBE,NOTIFY,REFER,MESSAGE,PUBLISH
Content-Type: application/sdp
Accept: application/sdp, multipart/mixed
Accept-Encoding: identity
Content-Length:   277

v=0
o=user 12824182 12824182 IN IP6 xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
s=-
c=IN IP6 xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
t=0 0
m=audio 7078 RTP/AVP 8 110
a=rtpmap:8 PCMA/8000
a=rtpmap:110 telephone-event/8000
a=fmtp:110 0-15
a=sendrecv
a=rtcp:7079
a=ptime:20


ACK sip:4900000000@[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx];uniq=8ED0C01913346AA654117F901E24D SIP/2.0
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
Via: SIP/2.0/UDP [yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];branch=z9hG4bKd674.6295c199c1d6f3d7c65df5051cc1bd86.0
Via: SIP/2.0/UDP ccc.ccc.cc.ccc;branch=z9hG4bKd674.9ae26c2d53df7a32d7cc5201eef22b18.0
Via: SIP/2.0/UDP ddd.ddd.ddd.ddd;branch=z9hG4bKd674.398f61cd1fb592c16403d50538fc8421.0
Via: SIP/2.0/UDP ee.eee.eee.ee:5060;branch=z9hG4bK2j5dam10a02iqjq1gn00.1
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
From: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
To: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
CSeq: 1 ACK
Max-Forwards: 61
Content-Length: 0


BYE sip:+491111111111@ee.eee.eee.ee:5060;user=phone;transport=udp SIP/2.0
Via: SIP/2.0/UDP [xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:5060;rport;branch=z9hG4bK66826E59C0886604
Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773;did=637.7591>
Route: <sip:ddd.ddd.ddd.ddd;lr=on>
From: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
To: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 2 BYE
X-RTP-Stat: CS=0;PS=3811;ES=3889;OS=609760;SP=0/0;SO=0;QS=-;PR=3853;ER=3889;OR=616480;CR=0;SR=0;QR=-;PL=0,0;BL=0;LS=0;RB=0/0;SB=-/-;EN=PCMA;DE=PCMA;JI=23,1;DL=67,67,70;IP=[xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:7078,[hhhh:hhh:hhh::hhh:hhh:hhh:hh]:20798
X-RTP-Stat-Add: DQ=2;DSS=0;DS=0;PLCS=32;JS=1
X-SIP-Stat: DRT=0;IR=0
Reason: Q.850; cause=16
Max-Forwards: 70
User-Agent: AVM FRITZ!Box 7490 (UI) 113.07.29 (Oct 26 2021)
Supported: 100rel,replaces
Allow-Events: telephone-event,refer
Content-Length: 0


SIP/2.0 200 OK
Via: SIP/2.0/UDP [xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]:5060;received=xxxx:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx;rport=5060;branch=z9hG4bK66826E59C0886604
From: "+4900000000" <sip:+4900000000@sip-proxy.de;user=phone>;tag=0D99F03B986ED6CD
To: "+491111111111" <sip:+491111111111@sip-server.de;user=phone>;tag=n6719nbq-CC-1031-OFC-1773
Call-ID: b6a6a84q4nw41b9icb46b1441ccbzcnv@zz.zz.z.zz
CSeq: 2 BYE
Record-Route: <sip:ddd.ddd.ddd.ddd;lr=on>
Record-Route: <sip:ccc.ccc.cc.ccc;lr=on;ftag=n6719nbq-CC-1031-OFC-1773>
Record-Route: <sip:bbb.bbb.bbb.bbb;r2=on;lr=on>
Record-Route: <sip:[yyyy:yyy:yyy:yyy:yyy:yyy:yyy:yyy];r2=on;lr=on>
Content-Length: 0


```

### Possible Solutions

Nothing.

### Additional Information

  * **Kamailio Version** - output of `kamailio -v`

```RUST
version: kamailio 5.3.9 (x86_64/linux) 
flags: USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, USE_RAW_SOCKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES, TLS_PTHREAD_MUTEX_SHARED
ADAPTIVE_WAIT_LOOPS 1024, MAX_RECV_BUFFER_SIZE 262144, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id:  
compiled with gcc 8.3.0
```

* **Operating System**:

```RUST
Linux sip-proxy2 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64 GNU/Linux
```
