### ISSUE TITLE
kamailio 4.3.1: segfault when using tls and cli params

### ISSUE THREAD

**Issue by dunst0** [kamailio/kamailio#374]
When using -u or -g cli params

```
root@sip:~ # kamailio -u kamailio -g kamailio
loading modules under config path: /usr/local/lib/kamailio/modules/
Listening on 
             udp: x.x.x.x:5060
             udp: 127.0.0.1:5060
             tcp: x.x.x.x:5060
             tcp: 127.0.0.1:5060
Aliases: 
             tcp: localhost.my.domain:5060
             tcp: localhost:5060
             udp: localhost.my.domain:5060
             udp: localhost:5060

```

```
root@sip:~ # kamailio -u kamailio -g kamailio
loading modules under config path: /usr/local/lib/kamailio/modules/
ERROR: bad config file (2 errors)
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x0000000805cb3200 in ?? ()
#1  0x000000000078fb0d in destroy_tls ()
#2  0x0000000000512fd1 in cleanup ()
#3  0x000000000051a91a in handle_sigs ()
#4  0x0000000000532441 in main ()
(gdb) 
```
